language: node_js
install: travis_wait 50 mvn install
sudo: false
node_js:
  - "stable"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
before_deploy:
  - gulp deploy:test:css
  - gulp deploy:test:html
  - sed -i '/target/d' .gitignore
  - sed -i '/deploy/d' .gitignore
